name: mypy

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - uses: jpetrucciani/mypy-check@master
        with:
          path: lnbits
